{{- if .Values.openshift.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "kubernetes-mcp-server.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- with .Values.openshift.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
