{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-mcp-server.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-mcp-server.serviceAccountName" . }}-{{ .Values.rbac.clusterRole | default "cluster-admin" }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-mcp-server.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole | default "cluster-admin" }}
{{- end }}
