# Control de habilitaciÃ³n de aplicaciones
applications:
  rhoai:
    enabled: true

  discounts:
    enabled: true
  
  inference:
    enabled: false
  
  kubernetesMcp:
    enabled: true
  
  llamaStack:
    enabled: true

  milvus:
    enabled: true

  minio:
    enabled: true
