# Control de habilitación de aplicaciones
applications:
  discounts:
    enabled: true
  
  inference:
    enabled: false
  
  kubernetesMcp:
    enabled: true
  
  llamaStack:
    enabled: true

# Configuración para llama-stack (token VLLM)
secret:
  data:
    VLLM_API_TOKEN: ""

