apiVersion: v2
name: minio
description: A Helm chart for deploying MinIO object storage for Data Science Pipelines
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - minio
  - object-storage
  - s3
  - data-science-pipelines
maintainers:
  - name: dseveria

