apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  name: rhods-operator
  channel: {{ .Values.operator.channel }}
  source: {{ .Values.operator.source }}
  sourceNamespace: {{ .Values.operator.sourceNamespace }}
  startingCSV: {{ .Values.operator.startingCSV }}

