apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
type: Opaque
stringData:
  {{ .Values.credentials.accessKeyName }}: {{ .Values.credentials.accessKey }}
  {{ .Values.credentials.secretKeyName }}: {{ .Values.credentials.secretKey }}

