{{- if .Values.config.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    openshift.io/display-name: {{ .Values.global.name }}
  name: {{ .Values.global.name }}-config
  namespace: {{ .Values.global.namespace }}
data:
  run.yaml: |-
    {{ $file := $.Values.config.file }}
    {{- tpl ($.Files.Get $file) . | nindent 4 }}
{{- end }}
