# NetworkPolicy to allow llama-stack to access DSPA API
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-llama-stack-to-dspa
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ds-pipeline-dspa
      component: data-science-pipelines
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: llama-stack-example
      ports:
        - protocol: TCP
          port: 8888
        - protocol: TCP
          port: 8887

